### ISSUE TITLE
It just do nothing

### ISSUE THREAD

**Issue by YordanYanakiev** [peter-evans/nominatim-docker#32]
Hello. I've installed the image
with `docker pull peterevans/nominatim`
then I have executed
`docker run -d -p 8080:8080 -e NOMINATIM_PBF_URL='http://download.geofabrik.de/europe-latest.osm.pbf' --name nominatim peterevans/nominatim:latest`

but seems like nothing happens. I got nothing on localhost:8080, nor it seems that anything is downloading since there is no network activity.

Please help.

**Comment by peter-evans** [comment]
Hi @YordanYanakiev 

Please test with the example in the readme first. The example in the readme uses data for the Maldives which will build quickly. You are trying to build a database for the whole of Europe which will take many hours to complete and probably should be done in the cloud on a machine with higher performance than your local machine. You aren't getting any response from the container because it's still building.
